"""servedeck.wire — generated client configs (REDESIGN-2026-09-12.md §2.4).

The three ``render_*`` functions are PURE: given a :class:`servedeck.models.Registry`
and the CURRENT content of a client config file (as a string — ``""`` when the file
does not exist yet), each returns the new content. No filesystem access, no
`$HOME`, so they are fully testable with tmp_path-written fixtures.

Resolving ``ctx = "native"`` to an integer needs the local hub cache
(:func:`servedeck.models.native_ctx`), which IS I/O — so it is injected as a
``resolve_ctx`` callable rather than done inside the pure functions. Production
callers get one from :func:`make_default_ctx_resolver`; tests pass a trivial
dict-backed one and never touch ``$HOME``.

Every generator EDITS its own tables in place and leaves the rest of the file
byte-for-byte untouched (comments included) — a full parse-and-re-serialize
through ``tomllib``/``tomli_w`` would silently drop every hand-written comment
in ``~/.codex/config.toml``, which is exactly the "clobber" the packet's
instructions rule out. ``tomli_w`` is used only to render the VALUE of one
table at a time (correct quoting/escaping), never to rewrite the whole file.
"""

from __future__ import annotations

import difflib
import json
import tomllib
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import tomli_w

from . import models as _models
from . import paths as _paths

__all__ = [
    "GATEWAY_BASE_URL",
    "CHAT_COMPLETIONS_URL",
    "VSCODE_CHAT_LM_PATH",
    "CODEX_CONFIG_PATH",
    "KIMI_CONFIG_PATH",
    "WIRE_TARGETS",
    "CtxResolver",
    "render_vscode",
    "render_codex",
    "render_kimi",
    "make_default_ctx_resolver",
    "read_existing",
    "unified_diff",
    "WireTarget",
]

GATEWAY_BASE_URL = "http://127.0.0.1:8010"
#: VS Code's chatLanguageModels.json is specified (and today written) with
#: "localhost", not "127.0.0.1" — Codex/Kimi's base_url uses 127.0.0.1. Kept
#: as two constants rather than one so a future edit cannot quietly make them
#: agree by accident.
CHAT_COMPLETIONS_URL = "http://localhost:8010/v1/chat/completions"

VSCODE_CHAT_LM_PATH = Path.home() / ".config" / "Code" / "User" / "chatLanguageModels.json"
CODEX_CONFIG_PATH = Path.home() / ".codex" / "config.toml"
KIMI_CONFIG_PATH = Path.home() / ".kimi-code" / "config.toml"

#: Where `servedeck wire --apply` backs up a file before overwriting it:
#: state/backups/<YYYY-MM-DD>/<safe-name>.
BACKUP_ROOT = _paths.STATE_DIR / "backups"

#: Prepended to every table servedeck owns, so a human editing the file by hand
#: knows a `wire --apply` will overwrite it.
_OWNED_COMMENT = "# servedeck-generated by `servedeck wire` — edits here are overwritten."

CtxResolver = Callable[[_models.Model], int]


# --------------------------------------------------------------------------- #
# VS Code — chatLanguageModels.json (JSON: full parse/re-serialize is safe,
# there are no comments to lose).
# --------------------------------------------------------------------------- #

_VSCODE_GROUP_NAME = "servedeck"
#: The legacy local_llm-era group name this migrates in place, so `wire` does
#: not leave a stale duplicate group sitting next to the new one.
_VSCODE_OWNED_NAMES = frozenset({_VSCODE_GROUP_NAME, "local_llm"})
_DEFAULT_MAX_OUTPUT_TOKENS = 4096


def _vscode_entry(served_name: str, m: _models.Model, ctx: int) -> dict[str, Any]:
    max_out = m.max_output_tokens if m.max_output_tokens is not None else _DEFAULT_MAX_OUTPUT_TOKENS
    return {
        "id": served_name,
        "name": served_name,
        "url": CHAT_COMPLETIONS_URL,
        "toolCalling": True,
        "vision": m.vision,
        "maxInputTokens": max(ctx - max_out, 0),
        "maxOutputTokens": max_out,
    }


def render_vscode(
    registry: _models.Registry, existing_text: str, *, resolve_ctx: CtxResolver
) -> str:
    """One VS Code custom-endpoint group named "servedeck", one model entry per
    served id AND per preset. Any OTHER group in the array (a different vendor,
    or one the user added by hand) is passed through untouched."""
    if existing_text.strip():
        try:
            groups = json.loads(existing_text)
        except json.JSONDecodeError as e:
            raise ValueError(f"existing chatLanguageModels.json is not valid JSON: {e}") from e
        if not isinstance(groups, list):
            raise ValueError("chatLanguageModels.json must be a JSON array at the top level")
    else:
        groups = []

    entries: list[dict[str, Any]] = []
    for m in registry.models.values():
        ctx = resolve_ctx(m)
        entries.append(_vscode_entry(m.id, m, ctx))
        for preset_name in m.presets:
            entries.append(_vscode_entry(preset_name, m, ctx))

    new_group = {
        "name": _VSCODE_GROUP_NAME,
        "vendor": "customendpoint",
        "apiType": "chat-completions",
        "models": entries,
    }

    out: list[Any] = []
    replaced = False
    for g in groups:
        if isinstance(g, dict) and g.get("name") in _VSCODE_OWNED_NAMES:
            if not replaced:
                out.append(new_group)
                replaced = True
            continue  # drop a second owned group rather than duplicate it
        out.append(g)
    if not replaced:
        out.append(new_group)

    return json.dumps(out, indent=4) + "\n"


# --------------------------------------------------------------------------- #
# Comment-preserving TOML table surgery, shared by Codex and Kimi.
# --------------------------------------------------------------------------- #


def _find_top_level_section(text: str, header: str) -> tuple[int, int] | None:
    """Byte span of the table starting at the line ``header`` (exact match,
    trailing whitespace ignored), up to but not including the next line that
    starts with ``[`` (any top-level or dotted table header) or EOF. ``None``
    if ``header`` does not appear as its own line."""
    lines = text.splitlines(keepends=True)
    start = None
    for i, line in enumerate(lines):
        if line.rstrip("\n").rstrip("\r") == header:
            start = i
            break
    if start is None:
        return None
    end = len(lines)
    for j in range(start + 1, len(lines)):
        if lines[j].startswith("["):
            end = j
            break
    start_off = sum(len(l) for l in lines[:start])
    end_off = sum(len(l) for l in lines[:end])
    return start_off, end_off


def _render_table_values(data: dict[str, Any]) -> str:
    """key = value lines for ``data``, correctly TOML-quoted/escaped, via
    tomli_w (never a hand-rolled f-string) — but only the VALUES; the header
    line is ours, not tomli_w's, so callers can use quoted-dotted headers
    tomli_w itself would render differently (e.g. Kimi's ``models."x/y"``)."""
    if not data:
        return ""
    dumped = tomli_w.dumps({"_": data})
    # dumped is '[_]\nkey = "val"\n...\n' — drop the synthetic header line.
    return "\n".join(dumped.splitlines()[1:])


def _upsert_section(
    text: str, header: str, data: dict[str, Any], *, owned_comment: bool = True
) -> str:
    """Replace the ``[header]`` table's body with ``data`` (adding a leading
    "generated" comment), or append a new block if the table is not present
    yet. Everything outside the (comment +) header + body span is untouched."""
    body = _render_table_values(data)
    block = (f"{_OWNED_COMMENT}\n" if owned_comment else "") + header + "\n"
    if body:
        block += body + "\n"
    block += "\n"

    span = _find_top_level_section(text, header)
    if span is not None:
        start, end = span
        # Absorb one preceding line if it is exactly our own comment, so
        # re-running wire does not stack duplicate comments above the header.
        prefix_end = start
        preceding = text[:start].splitlines(keepends=True)
        if preceding and preceding[-1].rstrip("\n") == _OWNED_COMMENT:
            prefix_end = start - len(preceding[-1])
        return text[:prefix_end] + block + text[end:]

    if not text:
        return block
    sep = "" if text.endswith("\n\n") else ("\n" if text.endswith("\n") else "\n\n")
    return text + sep + block


# --------------------------------------------------------------------------- #
# Codex — ~/.codex/config.toml
# --------------------------------------------------------------------------- #


def render_codex(
    registry: _models.Registry, existing_text: str, *, resolve_ctx: CtxResolver
) -> str:
    """One ``[model_providers.servedeck]`` and one ``[profiles.<key>]`` per
    model, keyed by the model's registry key (``codex --profile qwen27b``).
    Everything else in the file (other providers, other profiles, comments) is
    left exactly as it was.

    ``model_max_output_tokens`` is this packet's best-effort reading of
    ``local_llm/docs/CLIENTS.md``'s "xhigh needs a large max_tokens or you get
    an EMPTY response" warning — the exact config key this Codex build accepts
    for that is NOT verified against a running binary (none is installed on
    this box); see the P1 report's open questions.
    """
    text = existing_text
    text = _upsert_section(
        text,
        "[model_providers.servedeck]",
        {"name": "servedeck", "base_url": f"{GATEWAY_BASE_URL}/v1", "wire_api": "responses"},
    )
    for key, m in registry.models.items():
        data: dict[str, Any] = {"model_provider": "servedeck", "model": m.id}
        if m.max_output_tokens is not None:
            data["model_max_output_tokens"] = m.max_output_tokens
        text = _upsert_section(text, f"[profiles.{key}]", data)
    return text


# --------------------------------------------------------------------------- #
# Kimi — ~/.kimi-code/config.toml
# --------------------------------------------------------------------------- #


def _kimi_capabilities(m: _models.Model) -> list[str]:
    caps: list[str] = []
    if m.tools is not None:
        caps.append("tool_use")
    if m.reasoning is not None:
        caps.extend(["thinking", "always_thinking"])
    if m.vision:
        caps.append("image_in")
    return caps


def _merge_thinking_section(text: str) -> str:
    """``[thinking] enabled = true`` — REDESIGN owner rule "reasoning always
    on". Any OTHER key already in ``[thinking]`` (e.g. ``effort``) is kept."""
    header = "[thinking]"
    span = _find_top_level_section(text, header)
    existing: dict[str, Any] = {}
    if span is not None:
        start, end = span
        try:
            existing = tomllib.loads(text[start:end]).get("thinking", {})
        except tomllib.TOMLDecodeError:
            existing = {}
    merged = dict(existing)
    merged["enabled"] = True
    return _upsert_section(text, header, merged, owned_comment=False)


def render_kimi(
    registry: _models.Registry, existing_text: str, *, resolve_ctx: CtxResolver
) -> str:
    """One ``[providers.servedeck]``, one ``[models."servedeck/<key>"]`` per
    model, and ``[thinking] enabled = true``. Everything else (the managed
    kimi-code provider, other models, oauth, services) is left untouched."""
    text = existing_text
    text = _upsert_section(
        text,
        "[providers.servedeck]",
        {"type": "openai", "base_url": f"{GATEWAY_BASE_URL}/v1", "api_key": "local-no-auth"},
    )
    for key, m in registry.models.items():
        ctx = resolve_ctx(m)
        data = {
            "provider": "servedeck",
            "model": m.id,
            "max_context_size": ctx,
            "capabilities": _kimi_capabilities(m),
            "display_name": m.id,
        }
        text = _upsert_section(text, f'[models."servedeck/{key}"]', data)
    text = _merge_thinking_section(text)
    return text


# --------------------------------------------------------------------------- #
# Wiring it together for the CLI (servedeck/cli.py) — the only I/O in this file.
# --------------------------------------------------------------------------- #


def make_default_ctx_resolver(registry: _models.Registry) -> CtxResolver:
    """A real ``resolve_ctx``: ``ctx`` as-is when it is already an int, else
    :func:`servedeck.models.native_ctx` (reads the local hub cache), cached per
    model so a preset-bearing model's hub lookup happens once per CLI run."""
    cache: dict[str, int] = {}

    def resolve(m: _models.Model) -> int:
        if isinstance(m.ctx, int):
            return m.ctx
        if m.key not in cache:
            cache[m.key] = _models.native_ctx(m.repo)
        return cache[m.key]

    return resolve


def read_existing(path: Path) -> str:
    """A target file's current content, or ``""`` if it does not exist yet."""
    try:
        return path.read_text()
    except FileNotFoundError:
        return ""


def unified_diff(name: str, before: str, after: str) -> str:
    return "".join(
        difflib.unified_diff(
            before.splitlines(keepends=True),
            after.splitlines(keepends=True),
            fromfile=f"a/{name}",
            tofile=f"b/{name}",
        )
    )


@dataclass(frozen=True)
class WireTarget:
    name: str
    path: Path
    render: Callable[[_models.Registry, str, CtxResolver], str]


WIRE_TARGETS: tuple[WireTarget, ...] = (
    WireTarget("vscode chatLanguageModels.json", VSCODE_CHAT_LM_PATH, render_vscode),
    WireTarget("codex config.toml", CODEX_CONFIG_PATH, render_codex),
    WireTarget("kimi config.toml", KIMI_CONFIG_PATH, render_kimi),
)
